language: ruby

rvm:
  - 2.2.2
script:
  - bundle exec jekyll build
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success: 
  - bundle exec s3_website push
  - bundle exec ./invalidate.sh

